name: CI/CD Deployment to EC2

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/familytree-app:latest
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/familytree-app:latest
            docker stop familytree-container || true
            docker rm familytree-container || true
            docker run -d \
              --name familytree-container \
              -p 8080:3000 \
              -e NODE_ENV=production \
              -e PORT=3000 \
              -e MONGO="${{ secrets.MONGO }}" \
              -e jwt_secret="${{ secrets.jwt_secret }}" \
              -e CLIENT_ID="${{ secrets.CLIENT_ID }}" \
              -e CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}" \
              -e REFRESH_TOKEN="${{ secrets.REFRESH_TOKEN }}" \
              -e ACCESS_TOKEN="${{ secrets.ACCESS_TOKEN }}" \
              -e ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}" \
              -e FRONTEND_URL="${{ secrets.FRONTEND_URL }}" \
              ${{ secrets.DOCKER_USERNAME }}/familytree-app:latest
